### ISSUE TITLE
Cannot run README code

### ISSUE THREAD

**Issue by antononcube** [librasteve/raku-Math-Polygons#9]
I cannot run the README code, because I cannot install "SVD::Drawing".

```shell
> zef install SVG::Drawing
===> Searching for: SVG::Drawing
No candidates found matching identity: SVG::Drawing
```

I also made Google searches for  "SVG::Drawing" -- I got nothing I can use. 

It looks like the definition of "SVG::Drawing" that is supposed to be used is given in the blog post: ["Day 18 – An SVG Christmas Tree"](https://perl6advent.wordpress.com/2018/12/18/day-18-an-svg-christmas-tree/) .

**Comment by p6steve** [comment]
hi @antononcube - thanks for pointing this out - it seems that I have not been keeping the README.md in sync with the bin/synopsis - there is no SVG::Drawing now - the Drawing class is now defined in Math::Polygons itself, so the only prerequisite is SVG::Plot (which is loaded automatically with zef install Math::Polygon and which pulls in the core SVG module automatically). You can check this with zef info SVG::Plot to see if you have it installed.
